export interface Ward {
  id: string
  code: string
  name: string
  description?: string
  created_at?: string
  updated_at?: string
}

export interface PollingUnit {
  id: string
  code: string
  name: string
  ward_code?: string
  ward_id?: string
  address?: string
  latitude?: number
  longitude?: number
  registered_voters?: number
  description?: string
  created_at?: string
  updated_at?: string
  ward?: Ward
}

export interface SearchResult {
  type: "ward" | "polling_unit"
  code: string
  name: string
  description?: string
  ward_code?: string
}

export type Language = "en" | "yo" | "pcm" | "ha" | "ig"

export const translations = {
  en: {
    home: "Home",
    mapView: "Map View",
    about: "About",
    searchPrompt: "Search by polling unit name, code, or ward...",
    searchButton: "Search",
    startListening: "Start voice search",
    stopListening: "Stop listening",
    voiceNotSupported: "Voice search is not supported in your browser",
    lgaLabel: "Ibadan North LGA",
    heroTitle: "Find Your Polling Unit",
    heroSubtitle: "Easily locate your assigned polling unit in Ibadan North Local Government Area",
    browseMap: "Browse Map",
    voiceSearch: "Voice Search",
    wards: "Wards",
    pollingUnits: "Polling Units",
    languages: "Languages",
    availability: "Availability",
    browseByWard: "Browse by Ward",
    browseByWardSubtitle: "Select a ward to view its polling units",
    noWardsFound: "No wards found",
    noWardsSubtitle: "Please check back later",
    howItWorks: "How It Works",
    howItWorksSubtitle: "Find your polling unit in three simple steps",
    step1Title: "Search",
    step1Desc: "Enter your polling unit name, code, or ward name",
    step2Title: "Locate",
    step2Desc: "View your polling unit on the interactive map",
    step3Title: "Navigate",
    step3Desc: "Get directions to your polling unit location",
    aiAssistantName: "Ìrànlọ́wọ́",
    aiGreeting: "Hello! I'm Ìrànlọ́wọ́, your voting assistant. I'll help you find your polling unit and guide you there. How can I assist you today?",
    aiNavigationStart: "Navigation started. Follow the directions step by step.",
    aiNavigationProgress: "You are {minutes} minutes away from your polling unit.",
    aiArrival: "You've arrived at your polling unit! Thank you for exercising your right to vote.",
    aiEncouragement1: "You're doing great! Keep going.",
    aiEncouragement2: "Your vote matters. Keep moving!",
    aiEncouragement3: "Almost there! Continue.",
    aiTypePlaceholder: "Type your message...",
    speakNow: "Speak now...",
    navigate: "Navigate",
    startNavigation: "Start Navigation",
    getDirections: "Get Directions",
    allWards: "All Wards",
    registeredVoters: "Registered Voters",
    viewDetails: "View Details",
    footerTagline: "Empowering Nigerian voters with accessible polling information",
    quickLinks: "Quick Links",
    support: "Support",
    faq: "FAQ",
    contact: "Contact Us",
    reportIssue: "Report Issue",
    allRightsReserved: "All Rights Reserved",
  },
  yo: {
    home: "Ile",
    mapView: "Aworan Apejuwe",
    about: "Nipa",
    searchPrompt: "Wa nipasẹ orukọ ẹka idibo, koodu, tabi agbegbe...",
    searchButton: "Wa",
    startListening: "Bẹrẹ wiwa ohun",
    stopListening: "Duro gbọ",
    voiceNotSupported: "Wiwa ohun ko ni atilẹyin ninu awoṣe rẹ",
    lgaLabel: "Ibadan North LGA",
    heroTitle: "Wa Ẹka Idibo Rẹ",
    heroSubtitle: "Rọrun lati wa ẹka idibo ti a fun ọ ni Ibadan North Local Government Area",
    browseMap: "Wo Apejuwe",
    voiceSearch: "Wiwa Ohun",
    wards: "Agbegbe",
    pollingUnits: "Ẹka Idibo",
    languages: "Ede",
    availability: "Wiwa",
    browseByWard: "Wo nipasẹ Agbegbe",
    browseByWardSubtitle: "Yan agbegbe kan lati wo awọn ẹka idibo rẹ",
    noWardsFound: "Ko si agbegbe ti a rii",
    noWardsSubtitle: "Jọwọ ṣe ayẹwo pada ni iṣẹju diẹ",
    howItWorks: "Bawo Ni O Ṣe Nṣẹ",
    howItWorksSubtitle: "Wa ẹka idibo rẹ ni awọn igbesẹ mẹta tọọ",
    step1Title: "Wa",
    step1Desc: "Tẹ orukọ ẹka idibo rẹ, koodu, tabi orukọ agbegbe",
    step2Title: "Wa Ibi",
    step2Desc: "Wo ẹka idibo rẹ lori apejuwe ti o nṣiṣẹ",
    step3Title: "Ṣe Itọsọna",
    step3Desc: "Gba itọsọna si ibi ẹka idibo rẹ",
    aiAssistantName: "Ìrànlọ́wọ́",
    aiGreeting: "Ẹ kú àbọ̀! Mo jẹ́ Ìrànlọ́wọ́, olùrànlọ́wọ́ ìdìbò rẹ. Màá ràn ọ́ lọ́wọ́ láti wá ibi ìdìbò rẹ kí n sì tọ́ ọ síbẹ̀. Báwo ni mo ṣe lè ràn ọ́ lọ́wọ́ lónìí?",
    aiNavigationStart: "Ìtọ́sọ́nà ti bẹ̀rẹ̀. Tẹ̀síwájú ní ìgbésẹ̀ kan lẹ́yìn ìgbésẹ̀ kan.",
    aiNavigationProgress: "O wà ní {minutes} ìṣẹ́jú sí ibi ìdìbò rẹ.",
    aiArrival: "O ti dé ibi ìdìbò rẹ! O ṣeun fún lílo ẹ̀tọ́ rẹ láti dìbò.",
    aiEncouragement1: "O ń ṣe dáadáa! Tẹ̀síwájú.",
    aiEncouragement2: "Ìbò rẹ ṣe pàtàkì. Máa lọ!",
    aiEncouragement3: "O ti fẹ́rẹ̀ẹ́ dé! Tẹ̀síwájú.",
    aiTypePlaceholder: "Tẹ ìfiránsẹ́ rẹ...",
    speakNow: "Sọ̀rọ̀ nísinsin yìí...",
    navigate: "Ìtọ́sọ́nà",
    startNavigation: "Bẹ̀rẹ̀ Ìtọ́sọ́nà",
    getDirections: "Gba Ìtọ́sọ́nà",
    allWards: "Gbogbo Àwọn Agbegbe",
    registeredVoters: "Àwọn Oníbò Tí A Forúkọ",
    viewDetails: "Wo Àlàyé",
    footerTagline: "Fífún àwọn oníbò Nigeria lágbára pẹ̀lú àlàyé ibi ìdìbò tí ó rọrùn láti rí",
    quickLinks: "Àwọn Àjápọ̀ Kíákíá",
    support: "Àtìlẹ́yìn",
    faq: "Àwọn Ìbéèrè Tí A Sábà Béèrè",
    contact: "Kàn Sí Wa",
    reportIssue: "Jábọ̀ Ìṣòro",
    allRightsReserved: "Gbogbo ẹ̀tọ́ ni a pamọ́",
  },
  pcm: {
    home: "Haus",
    mapView: "Map View",
    about: "About",
    searchPrompt: "Sach by polling unit name, code, or ward...",
    searchButton: "Sach",
    startListening: "Stat voice sach",
    stopListening: "Stop dey listen",
    voiceNotSupported: "Voice sach no dey support for your browser",
    lgaLabel: "Ibadan North LGA",
    heroTitle: "Find Your Polling Unit",
    heroSubtitle: "Easy to find your polling unit wey dem give you for Ibadan North Local Government Area",
    browseMap: "Browse Map",
    voiceSearch: "Voice Sach",
    wards: "Wards",
    pollingUnits: "Polling Units",
    languages: "Languages",
    availability: "Availability",
    browseByWard: "Browse by Ward",
    browseByWardSubtitle: "Choose one ward to see im polling units",
    noWardsFound: "No wards dey",
    noWardsSubtitle: "Abeg check back later",
    howItWorks: "How E Dey Work",
    howItWorksSubtitle: "Find your polling unit for three simple steps",
    step1Title: "Sach",
    step1Desc: "Enter your polling unit name, code, or ward name",
    step2Title: "Locate",
    step2Desc: "See your polling unit for the interactive map",
    step3Title: "Navigate",
    step3Desc: "Get direction to your polling unit location",
    aiAssistantName: "Ìrànlọ́wọ́",
    aiGreeting: "Hello! Na me be Ìrànlọ́wọ́, your voting helper. I go help you find your polling unit and carry you go there. Wetin you want make I help you with today?",
    aiNavigationStart: "Navigation don start. Follow direction step by step.",
    aiNavigationProgress: "You dey {minutes} minutes away from your polling unit.",
    aiArrival: "You don reach your polling unit! Thank you say you come vote.",
    aiEncouragement1: "You dey do well! Continue.",
    aiEncouragement2: "Your vote important. Continue dey go!",
    aiEncouragement3: "Almost reach! Continue.",
    aiTypePlaceholder: "Type your message...",
    speakNow: "Talk now...",
    navigate: "Navigation",
    startNavigation: "Start Navigation",
    getDirections: "Get Direction",
    allWards: "All Wards",
    registeredVoters: "Registered Voters",
    viewDetails: "View Details",
        footerTagline: "Helping Nigerian voters find polling information easy",
    quickLinks: "Quick Links",
    support: "Support",
    faq: "Questions Dem Dey Ask",
    contact: "Contact Us",
    reportIssue: "Report Problem",
    allRightsReserved: "All rights reserved",
    locationError: "We no fit find your location. Make you allow location access.",
    mapNotAvailable: "Map markers no dey",
  },
  ha: {
    home: "Gida",
    mapView: "Duba Taswira",
    about: "Game da",
    searchPrompt: "Nemo ta sunan wurin zabe, lamba, ko gunduma...",
    searchButton: "Nemo",
    startListening: "Fara sauraren murya",
    stopListening: "Dakatar da saurare",
    voiceNotSupported: "Binciken murya baya goyan bayan a cikin browser ɗin ku",
    lgaLabel: "Ibadan North LGA",
    heroTitle: "Nemo Wurin Zabe Naka",
    heroSubtitle: "Sauki don nemo wurin zabe da aka ba ka a Ibadan North Local Government Area",
    browseMap: "Duba Taswira",
    voiceSearch: "Bincike da Murya",
    wards: "Gundumomi",
    pollingUnits: "Wuraren Zabe",
    languages: "Harsuna",
    availability: "Samuwa",
    browseByWard: "Duba ta Gunduma",
    browseByWardSubtitle: "Zaɓi gunduma don duba wuraren zabe",
    noWardsFound: "Ba a sami gundumomi ba",
    noWardsSubtitle: "Da fatan za a sake duba daga baya",
    howItWorks: "Yadda Yake Aiki",
    howItWorksSubtitle: "Nemo wurin zabe naka cikin matakai uku masu sauƙi",
    step1Title: "Nemo",
    step1Desc: "Shigar da sunan wurin zabe, lamba, ko sunan gunduma",
    step2Title: "Gano Wuri",
    step2Desc: "Duba wurin zabe naka akan taswira mai aiki",
    step3Title: "Shirya Tafiya",
    step3Desc: "Samu jagororin zuwa wurin zabe naka",
    aiAssistantName: "Ìrànlọ́wọ́",
    aiGreeting: "Sannu! Ni ne Ìrànlọ́wọ́, mataimakin zabe naka. Zan taimake ka nemo wurin zabe naka kuma in jagorance ka zuwa can. Yaya zan iya taimaka maka a yau?",
    aiNavigationStart: "An fara jagoranci. Bi jagororin mataki-mataki.",
    aiNavigationProgress: "Kana da mintuna {minutes} daga wurin zabe naka.",
    aiArrival: "Kun isa wurin zabe naku! Na gode don amfani da haƙƙin ku na zabe.",
    aiEncouragement1: "Kuna yin kyau! Ci gaba.",
    aiEncouragement2: "Kuri'ar ku tana da mahimmanci. Ci gaba da tafiya!",
    aiEncouragement3: "Kusan zuwa! Ci gaba.",
    aiTypePlaceholder: "Rubuta saƙonka...",
    speakNow: "Yi magana yanzu...",
    navigate: "Shirya Tafiya",
    startNavigation: "Fara Jagoranci",
    getDirections: "Samu Jagorori",
    allWards: "Duk Gundumomi",
    registeredVoters: "Masu Jefa Kuri'a da aka Yiwa Rajista",
    viewDetails: "Duba Cikakkun Bayanai",
    footerTagline: "Ƙarfafa masu jefa kuri'a na Najeriya tare da bayanan zabe masu sauƙi",
    quickLinks: "Hanyoyin Hanzari",
    support: "Taimako",
    faq: "Tambayoyi da Ake Yi",
    contact: "Tuntuɓe Mu",
    reportIssue: "Bayar da Rahoto Game da Matsala",
    allRightsReserved: "Duk haƙƙoƙi an keɓe su",
    locationError: "Ba za mu iya gano wurin ku ba. Da fatan za ka ba da izinin samun wuri.",
    mapNotAvailable: "Alamomin taswira ba su nan",
  },
  ig: {
    home: "Ụlọ",
    mapView: "Lelee Map",
    about: "Banyere",
    searchPrompt: "Chọọ site na aha ebe ịtụ vootu, koodu, ma ọ bụ ward...",
    searchButton: "Chọọ",
    startListening: "Malite ịnụ olu",
    stopListening: "Kwụsị ịnụ",
    voiceNotSupported: "Achọ olu anaghị akwado na ihe nchọgharị gị",
    lgaLabel: "Ibadan North LGA",
    heroTitle: "Chọta Ebe Ịtụ Vootu Gị",
    heroSubtitle: "Dị mfe ịchọta ebe ịtụ vootu e kenyere gị na Ibadan North Local Government Area",
    browseMap: "Lelee Map",
    voiceSearch: "Chọọ Olu",
    wards: "Wards",
    pollingUnits: "Ebe Ịtụ Vootu",
    languages: "Asụsụ",
    availability: "Dị",
    browseByWard: "Lelee Site na Ward",
    browseByWardSubtitle: "Họrọ ward iji hụ ebe ịtụ vootu ya",
    noWardsFound: "Achọtaghị wards",
    noWardsSubtitle: "Biko legharịa anya ma emechaa",
    howItWorks: "Otu O Si Arụ Ọrụ",
    howItWorksSubtitle: "Chọta ebe ịtụ vootu gị n'ime nzọụkwụ atọ dị mfe",
    step1Title: "Chọọ",
    step1Desc: "Tinye aha ebe ịtụ vootu gị, koodu, ma ọ bụ aha ward",
    step2Title: "Chọta Ebe",
    step2Desc: "Lelee ebe ịtụ vootu gị na map na-arụ ọrụ",
    step3Title: "Duzie",
    step3Desc: "Nweta ntụziaka gaa na ebe ịtụ vootu gị",
    aiAssistantName: "Ìrànlọ́wọ́",
    aiGreeting: "Ndewo! Abụ m Ìrànlọ́wọ́, onye enyemaka ịtụ vootu gị. Aga m enyere gị aka ịchọta ebe ịtụ vootu gị ma duzie gị ebe ahụ. Kedu ihe m nwere ike inyere gị aka taa?",
    aiNavigationStart: "Ebidola iduzi. Soro ntụziaka nzọụkwụ nzọụkwụ.",
    aiNavigationProgress: "Ị nọ nkeji {minutes} site na ebe ịtụ vootu gị.",
    aiArrival: "Ị rutela ebe ịtụ vootu gị! Daalụ maka iji ikike gị ịtụ vootu.",
    aiEncouragement1: "Ị na-eme nke ọma! Gaa n'ihu.",
    aiEncouragement2: "Vootu gị dị mkpa. Gaa n'ihu!",
    aiEncouragement3: "Ọ fọdụrụ nke nta! Gaa n'ihu.",
    aiTypePlaceholder: "Pịnye ozi gị...",
    speakNow: "Kwuo ugbu a...",
    navigate: "Duzie",
    startNavigation: "Malite Iduzi",
    getDirections: "Nweta Ntụziaka",
    allWards: "Wards Niile",
    registeredVoters: "Ndị Tụrụ Vootu Edebanyere Aha",
    viewDetails: "Lelee Nkọwa",
    footerTagline: "Na-enye ndị na-atụ vootu Naịjirịa ike site na ozi ịtụ vootu dị mfe",
    quickLinks: "Njikọ Ngwa Ngwa",
    support: "Nkwado",
    faq: "Ajụjụ A Na-ajụkarị",
    contact: "Kpọtụrụ Anyị",
    reportIssue: "Kọọ Nsogbu",
    allRightsReserved: "Echekwara ikike niile",
    locationError: "Anyị enweghị ike ịchọta ebe ị nọ. Biko nye ohere ịnweta ebe.",
    mapNotAvailable: "Ihe nrịbama map adịghị",
  },
} as const


